import PDFDocument from 'pdfkit';

const TERM_LABELS = [
  ['holdingHandsHugging',   'Holding Hands & Hugging'],
  ['kissingAffection',      'Kissing & Affection'],
  ['touchingAboveClothing', 'Touching Above Clothing'],
  ['touchingUnderClothing', 'Touching Under Clothing'],
  ['sexualIntimacy',        'Sexual Intimacy'],
  ['photosVideo',           'Photos / Video'],
  ['overnightStays',        'Overnight Stays'],
];

function agreedTerms(record) {
  return TERM_LABELS.filter(([key]) => record[key]).map(([, label]) => label);
}

/** Builds a single-record PDF certificate. Returns the PDFDocument (a readable stream), already ended. */
export function buildRecordPDF(record, { requesterName, consenterName }) {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });

  doc.fontSize(20).font('Helvetica-Bold').text('Hookups — Consent Record', { align: 'center' });
  doc.moveDown(0.3);
  doc.fontSize(10).font('Courier').fillColor('#666').text(record.recordId, { align: 'center' });
  doc.fillColor('#000');
  doc.moveDown(1.5);

  doc.fontSize(12).font('Helvetica-Bold').text('Parties');
  doc.font('Helvetica').fontSize(11);
  doc.text(`Requester: ${requesterName}`);
  doc.text(`Consenter: ${consenterName}`);
  doc.moveDown(1);

  doc.font('Helvetica-Bold').text('Status');
  doc.font('Helvetica').text(`${record.status.toUpperCase()} — via ${record.method}`);
  doc.moveDown(1);

  doc.font('Helvetica-Bold').text('Timeline');
  doc.font('Courier').fontSize(10);
  doc.text(`Started:   ${new Date(record.startedAt).toISOString()}`);
  if (record.confirmedAt) doc.text(`Confirmed: ${new Date(record.confirmedAt).toISOString()}`);
  if (record.revokedAt)   doc.text(`Revoked:   ${new Date(record.revokedAt).toISOString()}`);
  doc.moveDown(1);

  doc.font('Helvetica-Bold').fontSize(12).text('Agreed Terms');
  doc.font('Helvetica').fontSize(11);
  const terms = agreedTerms(record);
  if (terms.length === 0) doc.text('(none)');
  // Helvetica's WinAnsi encoding has no ✓ glyph (it renders as a stray
  // apostrophe) — plain ASCII avoids that without embedding a custom font.
  for (const t of terms) doc.text(`- ${t}`);
  if (record.safeWord) doc.text(`Safe word: ${record.safeWord}`);
  doc.text(`Location sharing: ${record.locationSharing ? 'agreed by both parties' : 'not active'}`);
  if (record.placeName) doc.text(`Place: ${record.placeName}`);
  doc.moveDown(1);

  if (record.revokedAt) {
    doc.font('Helvetica-Bold').fontSize(12).text('Revocation');
    doc.font('Helvetica').fontSize(11).text(`Reason given: ${record.revokeReason || '(not shared)'}`);
    doc.moveDown(1);
  }

  doc.font('Helvetica-Bold').fontSize(12).text('Tamper-Evidence');
  doc.font('Courier').fontSize(8).fillColor('#333');
  doc.text(`Signature: ${record.signature ?? '(unsigned)'}`, { width: 495 });
  doc.text(`Chain hash: ${record.chainHash ?? '(none)'}`, { width: 495 });
  doc.fillColor('#000');

  doc.moveDown(2);
  doc.fontSize(8).font('Helvetica-Oblique').fillColor('#888').text(
    'Generated by Hookups. This document is not a substitute for legal advice.',
    { align: 'center' },
  );

  doc.end();
  return doc;
}

function csvEscape(value) {
  const s = String(value ?? '');
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

/** Builds a CSV string covering a set of records, one row per record. */
export function buildRecordsCSV(records) {
  const headers = [
    'recordId', 'status', 'method', 'requesterName', 'consenterName',
    'startedAt', 'confirmedAt', 'revokedAt', 'agreedTerms', 'safeWord',
    'locationSharing', 'placeName', 'signature', 'chainHash',
  ];
  const rows = records.map((r) => [
    r.recordId, r.status, r.method, r.requester?.fullName ?? '', r.consenter?.fullName ?? '',
    r.startedAt ? new Date(r.startedAt).toISOString() : '',
    r.confirmedAt ? new Date(r.confirmedAt).toISOString() : '',
    r.revokedAt ? new Date(r.revokedAt).toISOString() : '',
    agreedTerms(r).join('; '), r.safeWord ?? '',
    r.locationSharing ? 'yes' : 'no', r.placeName ?? '',
    r.signature ?? '', r.chainHash ?? '',
  ]);

  return [headers, ...rows].map((row) => row.map(csvEscape).join(',')).join('\n');
}
